### ISSUE TITLE
Invalid utf-8 sequence while running hello triangle

### ISSUE THREAD

**Issue by Edweis** [denoland/webgpu-examples#1] opened 2021-03-03 02:41 UTC
Hi I was trying [Deno new WebGPU](https://deno.land/posts/v1.8#experimental-support-for-the-webgpu-api) binding but I encounter this issue:
``` bash
$  deno run --unstable --allow-write=output.png https://raw.githubusercontent.com/crowlKats/webgpu-examples/f3b979f57fd471b11a28c5b0c91d0447221ba77b/hello-triangle/mod.ts
Download https://raw.githubusercontent.com/crowlKats/webgpu-examples/f3b979f57fd471b11a28c5b0c91d0447221ba77b/hello-triangle/mod.ts
Download https://raw.githubusercontent.com/crowlKats/webgpu-examples/f3b979f57fd471b11a28c5b0c91d0447221ba77b/utils.ts
Download https://raw.githubusercontent.com/crowlKats/webgpu-examples/f3b979f57fd471b11a28c5b0c91d0447221ba77b/deps.ts
Download https://deno.land/x/pngs@0.1.1/mod.ts
Download https://crux.land/2arQ9t
Download https://deno.land/x/gmath@0.1.2/mod.ts
Download https://deno.land/x/obj@0.0.2/mod.ts
Download https://www.cloudflare-terms-of-service-abuse.com/streaming.ts
Download https://www.cloudflare-terms-of-service-abuse.com/streaming.ts
Download https://www.cloudflare-terms-of-service-abuse.com/streaming.ts
Download https://crux.land/2arQ9t.ts
Download https://deno.land/x/byte_type@0.1.1/mod.ts
error: invalid utf-8 sequence of 1 bytes from index 6
    at https://raw.githubusercontent.com/crowlKats/webgpu-examples/f3b979f57fd471b11a28c5b0c91d0447221ba77b/deps.ts:2:0```

**Comment by crowlKats** [comment] 2021-03-07 08:34
@Edweis what OS are you on?

**Comment by crowlKats** [comment] 2021-03-07 08:44
nevermind, this actually is a duplicate of denoland/deno#9661

**Closed as completed by crowlKats** 2021-03-07 08:44 UTC
